### ISSUE TITLE
[Tarefa] - Diagramar Banco de Dados

### ISSUE THREAD

**Issue by AntonioRangelC** [EPS-DataMed/wiki#18]

**Comment by ArthurMeloG** [comment]
Diagrama realizado e ddl em postgresql



Diagrama: Visão lógica [diagrama.pdf](https://github.com/EPS-DataMed/wiki/files/15255962/diagrama.pdf)







Mapeamento de dados: [DDL.txt](https://github.com/EPS-DataMed/wiki/files/15255964/DDL.txt)

**Comment by Thiagof99** [comment]
Recriação do diagrama para se adequar ao software proposto

Diagrama: [DiagramaDB.pdf](https://github.com/EPS-DataMed/wiki/files/15400071/DiagramaDB.pdf)
