### ISSUE TITLE
US04 - Edição do dados cadastrais

### ISSUE THREAD

**Issue by AntonioRangelC** [EPS-DataMed/wiki#5]
# US04 - Edição do dados cadastrais

### Descrição 
**Eu, como:** Usuário

**Desejo:**  editar meus dados cadastrados

### Tarefas

- [ ] Tarefa 1

**Comment by dansousamelo** [comment]
Quando chamar a rota de listar um usuário deve vim as informações de médico se esse usuário for médico.

**Comment by dansousamelo** [comment]
## Débitos

1. Ao editar senha o usuário pode querer ver a senha [FRONT]
2. Ao editar senha enviar a senha anterior e a nova senha para o backend [FRONT e BACK]
3. Ao edita senha o backend deve validar se as senhas estão corretas e mandar os erros adequados [BACK]
4. Ao deletar um usuário o usuário pode querer ver a senha [FRONT]
5. Ao deletar um usuário enviar a senha para o backend e ver se está correta [FRONT e BACK]
6. Ajusta rota de PATCH [BACK]


### POST /user/verify-password/${user_id}

**Request:**
```json
{
    "password": "string"
}
```

**Response:**
```json
{
    "valid": boolean
}
```
